name: mikesite
favicon: null
layout_spectrum: 0.06469
typography_spectrum: 0.34351
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a06f4e'
    - '#e7ecef'
    - '#1b1e17'
    - '#9e9fa3'
    - '#514d41'
  brandStrength: 0.75
  lightness: 0.5491266683675349
  saturation: 0.7903528579045087
  rhythmicContrast: 0.875450964551419
purpose: []
